site_name: Projektauftrag 1
dev_addr: '0.0.0.0:80'

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - md_in_html
  
plugins:
  - encryptcontent:
      title_prefix: ''
      summary: 'Lösungen noch nicht vergügbar'
      placeholder: '... hier eingeben'
      decryption_failure_message: 'Hast du die Augabe schon gelost?'
      encryption_info_message: 'Passwort'
      password_button: True
      password_button_text: ' o '
theme:
  name: material
  language: de
  font: false
  favicon: favicon.png
  logo: favicon.png

site_author: "Victoria N. Meneghel"

extra_css:
    - css/extra.css

extra_javascript:
  - js/extra.js
    
nav:
  - Einleitung: index.md
  - Aufgaben: user-guide/aufgaben.md
  - Lösungen: user-guide/loesungen.md
  - Feedback: statistics/feedback.md
  - Impressum: legal/imprint.md

